### ISSUE TITLE
Opaque panel stays light when using dark style preference

### ISSUE THREAD

**Issue by marcelovbcfilho** [elementary/wingpanel#405] opened 2021-08-10 23:28 UTC
## What Happened

I don’t know if this is or isn’t a bug, it just look a little inconsistent, a you can see in the following image I set a wallpaper that causes the wingpanel to become white, but because I’m using the dark mode now, the wingpanel white looks a little disconnected from the rest of the system theme, as I said, I’m not sure if this is the supposed behavior.
![Screenshot from 2021-08-10 20-15-19](https://user-images.githubusercontent.com/51462138/128947532-86de6299-2f00-4868-8f28-8f2e121d5ce6.png)

## Expected Behavior

I think that what is supposed to happen is that if I’m using the dark mode the wingpanel color, if needed, should follow the theme mode, like become dark, only if the set wallpaper needs a wingpanel color, otherwise it should keep transparent.

## Steps to Reproduce

1.Set the wallpaper with a combination of colors to make the wingpanel become white.
![wall4](https://user-images.githubusercontent.com/51462138/128947438-d2451ada-c012-44b2-8728-470350a0dba8.jpg)
2.Set the style to dark

## Platform Information

Elementary OS 6 stable release, downloaded from the official site.

**Comment by cassidyjames** [comment] 2021-08-12 02:12
Hmm, I can see this both ways. On the one hand, yeah, it's bright white and that might be annoying/unexpected when using the dark style. On the other hand, the panel is white because the top of the wallpaper is white—and making the panel dark isn't going to make the wallpaper itself any darker.

My instinct is that it would feel more natural if the opaque panel was always dark in the dark style though.

**Comment by danirabbit** [comment] 2024-06-04 03:09
Closing as a duplicate of #389

**Closed by danirabbit** 2024-06-04 03:09 UTC
Labels: Needs Design
