### ISSUE TITLE
Indicators and icons not appearing in WingPanel

### ISSUE THREAD

**Issue by r3k4** [elementary/wingpanel#119] opened 2018-06-12 10:24 UTC
I'm having a issue with WingPanel. 
The Dropbox indicator isn't present at all.

I'm up to date on all packages, fresh install from ubuntu 18.04

**Comment by tintou** [comment] 2018-06-12 11:37
Dropbox use a 6 years old unsupported Indicator API
Closed as won't fix.

**Closed by tintou** 2018-06-12 11:37 UTC

**Comment by r3k4** [comment] 2018-06-13 11:17
@tintou not only dropbox, but also other applications is also not appearing in wingpanel.. like skype, steam, telegram, etc.

**Comment by donadigo** [comment] 2018-06-13 11:36
To be able to see them you need to install a special package which is a compatibility layer - "wingpanel-indicator-ayatana".

In terminal:
sudo apt install wingpanel-indicator-ayatana

**Comment by r3k4** [comment] 2018-06-13 16:35
@donadigo 
I have installed "wingpanel-indicator-ayatana", but still not appearing in tray.. is there any additional configuration for this ?

**Comment by cassidyjames** [comment] 2018-08-10 22:35
Duplicate of #96
