### ISSUE TITLE
No third-party application indicator displayed in wingpanel

### ISSUE THREAD

**Issue by ryonakano** [elementary/wingpanel#126] opened 2018-06-29 08:54 UTC
I'm not sure this is a bug or intentionally created feature, but there is no third-party application indicator (like Slack, Brasero, input methods, etc.) in wingpanel on Juno Daily.

**Comment by mdh34** [comment] 2018-06-29 10:18
Closing this as a duplicate of #96

**Comment by ryonakano** [comment] 2018-06-29 10:19
Oops, I'm sorry

**Closed by mdh34** 2018-06-29 10:18 UTC
