### ISSUE TITLE
Wingpanel move out of it's place

### ISSUE THREAD

**Issue by Inmer** [elementary/wingpanel#176] opened 2018-11-08 16:15 UTC
On touch screen when moving three fingers down from top bottom, I can place the wingpanel anywhere I want. To place it on top where it should be, I have to run this command: `killall wingpanel`

This gesture on my laptop:
![group-women-hand-use-multi-touch-gestures-tablets-touc-screen-device-51041872](https://user-images.githubusercontent.com/25564840/48211380-002a0a00-e33f-11e8-8c78-75a8c1d604fe.jpg)

Screenshots of the wingpanel out of it's place:
![screenshot from 2018-11-08 10-06-52](https://user-images.githubusercontent.com/25564840/48211095-5e0a2200-e33e-11e8-90c5-dbdca08d268a.png)

![screenshot from 2018-11-08 10-07-10](https://user-images.githubusercontent.com/25564840/48211116-69f5e400-e33e-11e8-9de9-0ef932cfb7cc.png)

**Comment by peteruithoven** [comment] 2018-11-08 17:03
I've tried returning `Gdk.EVENT_STOP` in the `Panel.button_press_event` but that doesn't seem to help.

**Comment by danrabbit** [comment] 2018-11-08 17:11
Gonna close this as a duplicate of #169

**Closed by danrabbit** 2018-11-08 17:11 UTC
