### ISSUE TITLE
Preload the application panel?

### ISSUE THREAD

**Issue by sprite-1** [elementary/wingpanel#182] opened 2018-12-21 22:33 UTC
Whenever I boot up eOS, even if I waited for a while, to make sure everything had "loaded" whenever I click to open the applications panel for the first time, it would take a while to open up (think a couple seconds or less). Then subsequent clicks to it opens it immediately.

I was wondering if we can have it so that on log in to the account, it preloads the contents of that panel so that it doesn't have to do that initial loading phase anymore?

**Comment by peteruithoven** [comment] 2018-12-21 22:35
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/applications-menu/issues/163

**Comment by sprite-1** [comment] 2018-12-21 22:36
Oh, I looked for "preload" and "pre load" in both open and clsoed issues :sweat_smile:

**Closed by peteruithoven** 2018-12-21 22:35 UTC
Labels: Status: Duplicate

**Comment by peteruithoven** [comment] 2018-12-21 23:41
No problem, don't hesitate to keep pointing out issues :)
