### ISSUE TITLE
Opaque panel should change color depending on dark/light style.

### ISSUE THREAD

**Issue by tnetenbaa** [elementary/wingpanel#531] opened 2024-05-20 05:44 UTC
### Problem

Currently, when "Panel Translucency" is toggled off, the panel is black no matter what style you have set, and can look jarring.

### Proposal

Panel should be white in light style, black in dark style.

**Comment by danirabbit** [comment] 2024-05-30 21:34
Hey thanks for the report! It looks like this might be a duplicate of https://github.com/elementary/wingpanel/issues/389

**Closed by danirabbit** 2024-05-30 21:34 UTC
