### ISSUE TITLE
Fallback theming for those that don't want to use the elementary theme

### ISSUE THREAD

**Issue by zesterer** [elementary/wingpanel#55] opened 2017-09-24 19:02 UTC
When using a theme that isn't the Elementary GTK theme, panel indicator menus appear with blurred text backgrounds, stray lines between elements, and other horrible ugliness.

I know that this is likely an issue related to Granite, but it would be nice if you could have some sort of visually acceptable fallback for themes that don't support Granite elements.

It's certainly easier than every GTK theme developer writing Granite-compliant additions to their theme.

If there's anything I can help with on this, I'm happy to give it a go. I don't have the time to do the work alone though.

**Comment by cassidyjames** [comment] 2018-03-01 03:09
Can we GResource a stylesheet, but have it as a lower priority than the system stylesheet?

**Comment by danrabbit** [comment] 2018-03-02 18:21
@cassidyjames unfortunately not. The `fallback` priority will be overwritten by the `menubar` class that the panel uses. That priority only works when there are no default classes associated with the widget

**Comment by danrabbit** [comment] 2018-07-07 10:41
Closing because this is a duplicate of #2

**Closed by danrabbit** 2018-07-07 10:41 UTC
Labels: Needs Design
