### ISSUE TITLE
Wingpanel freezes/crashes when clicking on Applications

### ISSUE THREAD

**Issue by cg-david** [elementary/wingpanel#196] opened 2019-02-25 10:49 UTC
My wingpanel freezes frequently, when I click on the upper left Applications icon. 

Calender, language, power and everything works, but as soon as I click on Applications, nothing works any longer. 

After `killall wingpanel`, I can use everything, until I want to access Applications. 
I know, this kind of problem statement won't help you much, so please tell me what should I do, to give you more insights in the problem. 

Thanks

**Comment by peteruithoven** [comment] 2019-02-25 11:08
Could this be a duplicate of https://github.com/elementary/wingpanel/issues/20 ?
It also includes advice on how to debug.

**Comment by donadigo** [comment] 2019-04-20 01:23
Can confirm, just happened to me.

**Closed** 2019-04-20 16:33 UTC

**Comment by peteruithoven** [comment] 2019-04-20 16:35
@cg-david could you try [compiling the latest applications-menu](https://github.com/elementary/applications-menu#building-and-installation) (and restarting wingpanel)? @donadigo [created a possible fix](https://github.com/elementary/applications-menu/pull/191).

**Comment by cg-david** [comment] 2019-04-25 15:02
I switched back to Ubuntu 18.04 - also because of other minor bugs like printer recognition etc. was easier. I do not have a private laptop atm, but would highly consider using elementaryOS there. However not in my work environment atm.
