### ISSUE TITLE
Bluetooth icon not showing up right

### ISSUE THREAD

**Issue by Fatih20** [elementary/wingpanel#306] opened 2020-04-02 15:28 UTC
## Prerequisites
- [-] I have searched open and closed issues for duplicates.

## Describe the bug
The bluetooth icon is not showing up properly, seems like it got moved to the side and cropped

![Screenshot from 2020-04-02 22 23 31](https://user-images.githubusercontent.com/51940383/78267274-fb1bbb00-7530-11ea-8496-05bdf94aae30.png)

### To Reproduce
1. Look at your top panel

### Expected behavior
For the icon to be displayed properly.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [-] I'm using the latest released stable version

**Comment by ryonakano** [comment] 2020-04-03 06:02
Thank you for your reporting, but I'll close this as a duplicate of elementary/wingpanel-indicator-bluetooth#89.

**Closed by ryonakano** 2020-04-03 06:02 UTC
