### ISSUE TITLE
Top panel is partially off the screen, doesn't respond to clicks or open app-launcher

### ISSUE THREAD

**Issue by Janiczek** [elementary/wingpanel#75] opened 2017-12-24 08:55 UTC
![screen](https://user-images.githubusercontent.com/149425/34325377-fac5421e-e88f-11e7-919e-1e3d46ad206a.png)

Since yesterday, my wingpanel is only partially visible, see the screenshot. Restarting it with
```
$ killall wingpanel; sleep 2; wingpanel &
```
doesn't really help anything. It disappears, then appears, but again in the same wrong spot.

Clicking on the partially visible part of the wingpanel doesn't do anything; can't open the Applications menu, calendar, etc. Even trying the command-line version of "open Applications menu" doesn't work:
```
$ wingpanel --toggle-indicator app-launcher
```

Versions:
```
$ wingpanel --version
[INFO 09:47:49.473245] Application.vala:154: System Panel version: 2.0.4
[INFO 09:47:49.473272] Application.vala:156: Kernel version: 4.13.10-041310-generic
```

I'm using the daily elementaryOS PPA alongside the stable one.
```
deb http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main
deb-src http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial main

deb http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main
deb-src http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial main
```

**Comment by Djaler** [comment] 2017-12-24 11:00
I can confirm this. Looks like last [commit](https://github.com/elementary/switchboard-plug-networking/commit/5a5867be186cf4cb4b97eabb3ded819f8db89def) breaks this.

**Comment by Djaler** [comment] 2017-12-24 11:01
`[11:00:40.302399 GLib-GObject-Warning] cannot register existing type 'NMSetting'
[11:00:40.302429 GLib-Critical] g_once_init_leave: assertion 'result != 0' failed
[11:00:40.302436 GLib-GObject-Critical] g_type_register_static: assertion 'parent_type > 0' failed
[FATAL 14:00:40.302480] [libnm] _nm_register_setting: assertion 'type != G_TYPE_INVALID' failed
[11:00:40.302491 GLib-Critical] g_once_init_leave: assertion 'result != 0' failed`

**Comment by donadigo** [comment] 2017-12-24 12:29
So, daily build of the network indicator received a port to the new libnm and it looks like we have a conflict between NetworkManager library versions, since the switchboard network plug didn't receive this port yet. A temporary workaround, would be just to remove the network indicator:

`sudo apt remove wingpanel-indicator-network`

And then restart wingpanel:

`killall wingpanel && wingpanel &`

**Comment by worldofpeace** [comment] 2017-12-26 00:38
Ugh annoying. But I didn't see the panel being partially off the screen btw.

**Comment by Nine-H** [comment] 2017-12-26 04:35
@donadigo while that works it's a pretty sucky solution, if you're on daily you can just install daily build (which works) with the following commands

```
nine@x1-stinkpad:~$ apt show -a wingpanel-indicator-network
Package: wingpanel-indicator-network
Version: 2.1.1+r301+pkg14~ubuntu0.4.1.1
Priority: optional
Section: x11
Maintainer: Cody Garver <cody@elementary.io>
Installed-Size: 446 kB
Depends: dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.4), libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.43.2), libgranite3 (>= 0.2.0), libgtk-3-0 (>= 3.11.5), libnm-glib4 (>= 0.9.10.0), libnm-gtk0 (>= 0.9.6.4), libnm-util2 (>= 0.9.10.0), libwingpanel-2.0-0
Enhances: wingpanel
Download-Size: 57.1 kB
APT-Manual-Installed: yes
APT-Sources: http://ppa.launchpad.net/elementary-os/stable/ubuntu xenial/main amd64 Packages
Description: WingPanel Network Indicator
 WingPanel Network Indicator

Package: wingpanel-indicator-network
Version: 2.1.1+pkg201712182229~daily~ubuntu0.4.1.1
Priority: optional
Section: x11
Maintainer: Cody Garver <cody@elementary.io>
Installed-Size: 467 kB
Depends: dconf-gsettings-backend | gsettings-backend, libc6 (>= 2.4), libgee-0.8-2 (>= 0.8.3), libglib2.0-0 (>= 2.43.2), libgranite4 (>= 0.2.0), libgtk-3-0 (>= 3.11.5), libnm0 (>= 1.0.0), libnma0 (>= 1.1.90), libwingpanel-2.0-0
Enhances: wingpanel
Download-Size: 61.2 kB
APT-Sources: http://ppa.launchpad.net/elementary-os/daily/ubuntu xenial/main amd64 Packages
Description: WingPanel Network Indicator
 WingPanel Network Indicator
nine@x1-stinkpad:~$ sudo apt install wingpanel-indicator-network=2.1.1+pkg201712182229~daily~ubuntu0.4.1.1
```
even better might be pinning the daily repo so that daily builds become default packages.

**Comment by Nine-H** [comment] 2017-12-28 08:59
on loki daily and now I'm getting a blank panel

```
nine@x1-stinkpad:~/Projects$ killall wingpanel && wingpanel --debug
[INFO 19:58:35.114754] Application.vala:154: System Panel version: 2.0.4
[INFO 19:58:35.114799] Application.vala:156: Kernel version: 4.10.0-42-generic
[DEBUG 19:58:35.158771] [Gtk] Connecting to session manager
[WARNING 19:58:35.160110] IndicatorManager.vala:211: Unable to scan indicators folder /usr/local/lib/wingpanel: Error opening directory '/usr/local/lib/wingpanel': No such file or directory
[DEBUG 19:58:35.162033] Settings.vala:163: Loading settings from schema 'org.pantheon.desktop.wingpanel'
```

**Comment by danrabbit** [comment] 2017-12-28 18:10
Closing this as it was already resolved in an update. Please be advised that Daily is not a stable update channel and you *WILL* encounter issues like this from time to time.

**Closed by danrabbit** 2017-12-28 18:10 UTC
