### ISSUE TITLE
Dropbox can't display on top panel.

### ISSUE THREAD

**Issue by jade28** [elementary/wingpanel#183] opened 2018-12-22 17:08 UTC
Hi guys!
I have been this issue on `Juno 5.0`, `Loki 0.4` work well.
Thanks! 🙏

**Comment by peteruithoven** [comment] 2018-12-22 17:16
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/wingpanel/issues/96
Please search in the issue queue for existing issues next time.

**Closed by peteruithoven** 2018-12-22 17:16 UTC
Labels: Status: Duplicate

**Comment by jade28** [comment] 2018-12-22 17:20
Thanks @peteruithoven  🙏.
