### ISSUE TITLE
Keyboard layouts change very slowly 

### ISSUE THREAD

**Issue by ArtemPopof** [elementary/wingpanel#197] opened 2019-02-25 19:25 UTC
I have Elementary OS 5.0 installed and 2 keyboard layouts: us and ru and it takes up to 2 seconds to switch between layouts. I cannot type anything while it changing, so it feels like micro hangs that are very annoying. I doesn't have such problems on other linux distros such as fedora or ubuntu. My laptop has N2020 Celeron processor, but I also have this issue on other PC's with Elementary OS 5.0.

**Comment by peteruithoven** [comment] 2019-02-25 19:31
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/gala/issues/220

**Closed** 2019-02-25 19:32 UTC
Labels: Status: Duplicate
