### ISSUE TITLE
Feature request: Compatibility with Qt's QSystemTrayIcon

### ISSUE THREAD

**Issue by willbelr** [elementary/wingpanel#202] opened 2019-03-23 15:03 UTC
I would like to port my applications to Elementary OS desktop environment. However, they rely heavily on the system tray icons, and it turns out that the wingpanel is not compatible with Qt. In the example below, Qt reports that there is no system tray available. I think that Qt rely on D-Bus to communicate with the systray. Here is a PyQt5 example (should return True):

```
#!/usr/bin/python3
import sys
from PyQt5 import QtWidgets

class TrayIcon(QtWidgets.QSystemTrayIcon):
    def __init__(self, parent):
        super().__init__()
        status = self.isSystemTrayAvailable()
        print(status)

if __name__== '__main__':
    app = QtWidgets.QApplication(sys.argv)
    tray = TrayIcon(app)
    sys.exit(app.exec_())
```

**Comment by cassidyjames** [comment] 2019-03-24 00:09
There is no "system tray" in elementary OS, Qt or otherwise. Consequently, this is a duplicate of #96

**Closed by cassidyjames** 2019-03-24 00:09 UTC

**Comment by willbelr** [comment] 2019-03-24 04:31
It is quite bold to call them deprecated just because Gnome decided to stop using them. AFAIK they still work on pretty much all other Linux DE, even those who switched to Wayland. At the right of the wingpanel there are a bunch of icons which are pretty much just like usual system tray icons, to handle sound, wifi, battery... How do you call those, and how to they differ?

More importantly, as you chose not to support QSystemTrayIcon how would a Qt project integrate such icons?

**Comment by cassidyjames** [comment] 2019-03-27 17:54
@willbelr system indicators in elementary OS are exactly that: **system** indicators. They exist for the **system**, i.e. the OS, to communicate system-wide state. They are not intended for applications to just throw whatever they want up there. It's not a matter of what "pretty much all other Linux DE" do, as elementary OS is a specific project with a specific opinionated design. Status icons were deprecated even before GNOME dropped them, I was pointing to GNOME as an example of another (likely most widely-used) DE that does not support them. Further, elementary OS does not cater to Qt development, as we've chosen to support and enforce GTK for all apps made available for elementary OS via AppCenter. So how an app written in an unsupported toolkit would implement an unsupported behavior/API is not really relevant. There has already been pages and pages of discussion on this topic at the linked #96 issue, please see that issue for all I have to say on this topic—including the recommended APIs to integrate with modern DEs and OSes like GNOME and elementary OS.
