### ISSUE TITLE
Locale styling changed after the last wingpanel update to white color over white background

### ISSUE THREAD

**Issue by nnmlss** [elementary/wingpanel#265] opened 2019-11-02 08:48 UTC
## Describe the bug

After the last update of the wingpanel the styling of locale indicator was changed - white text over a white backgroud, or black text over a black background depending of the color of the wallpaper. 

### Expected behavior

I don't think that this is a conscious decision made by the design team that's why I post it here - it is difficult to read the text of the locale only by the drop shadow effect.
I expect different colors of the text and background, even better will be if there is no background, only the text colored with the wingpanel style

### Screenshots or screen recordings

![Screenshot from 2019-11-02 10 32 26](https://user-images.githubusercontent.com/1779227/68068355-87486d00-fd5c-11e9-84a2-e43a76a3dd57.png)

## Platform Information

![Screenshot from 2019-11-02 10 42 16](https://user-images.githubusercontent.com/1779227/68068447-7ba97600-fd5d-11e9-8e74-0dab7c9f957d.png)

- [+] I'm using the latest released stable version

## Additional context

I'm using different GTK+ themes, but this stlye is the same no matter wich one I use including the default elementary theme.

**Comment by ryonakano** [comment] 2019-11-02 11:06
Closing as a duplicate of elementary/wingpanel-indicator-keyboard#56

**Closed by ryonakano** 2019-11-02 11:06 UTC
