### ISSUE TITLE
Feature Suggestion: Menu Bar on Top Panel

### ISSUE THREAD

**Issue by cuongw** [elementary/wingpanel#195] opened 2019-02-24 07:22 UTC
Hello `Elementary Team`,

I'm a crazy fan of `Elementary OS`. Before moved `eOS`, I had used `Unbuntu 16.04` and I think it is a perfect feature. I hope it will appear on `eOS`.

Thanks!  Have a good day!

**Comment by peteruithoven** [comment] 2019-02-24 09:25
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/wingpanel/issues/81

Also there have been many discussions on the subject:
https://www.reddit.com/r/elementaryos/comments/8m81e1/global_app_menu_in_top_panel/
https://elementaryos.stackexchange.com/questions/4159/how-to-get-application-menus-in-elementary-os
https://twitter.com/DanielFore/status/991836014070022144

**Closed by peteruithoven** 2019-02-24 09:25 UTC
Labels: Status: Duplicate
