### ISSUE TITLE
Strange behaviour when zoomed in

### ISSUE THREAD

**Issue by ezeveliz** [elementary/wingpanel#266] opened 2019-11-03 17:16 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
If you zoom in and then open multitasking, wingpanel will float to the middle of the screen.

![IMG_20191103_135755693](https://user-images.githubusercontent.com/24837065/68089030-c0a7d800-fe43-11e9-8817-d55df1b2a98c.jpg)

*Sorry for the photo, but i couldn't take a screenshot.

### To Reproduce
1. Zoom in with ⌘ + '+' 
2. Open multitasking with ⌘ + ↓

## Platform Information

![System Information](https://user-images.githubusercontent.com/24837065/68089094-39a72f80-fe44-11e9-838e-25765e0a1065.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by lenemter** [comment] 2023-04-27 03:47
Duplicate of https://github.com/elementary/gala/issues/1127

**Closed by lenemter** 2023-04-27 03:47 UTC
Labels: Status: Confirmed
