### ISSUE TITLE
App Indicator don't show up on Wingpanel (eOS 5.0 Juno)

### ISSUE THREAD

**Issue by remmyle1102** [elementary/wingpanel#161] opened 2018-10-17 08:28 UTC
None of my installed app which has indicator show up on Wingpanel. 
Such as Caprine, Dropbox.
Though all of them work fine on eOS Loki. But I you depreciate them on Juno.
But is there any way to bring them back?

**Comment by peteruithoven** [comment] 2018-10-17 11:11
Duplicate of: https://github.com/elementary/wingpanel/issues/96
More on the rationale: https://medium.com/elementaryos/developer-tips-backgrounding-system-integration-31c1f7226606#8625

**Closed by peteruithoven** 2018-10-17 11:11 UTC
