### ISSUE TITLE
In dual screen vertical layout windows cannot be dragged to the top screen

### ISSUE THREAD

**Issue by phocean** [elementary/wingpanel#86] opened 2018-01-27 11:49 UTC
A common and ergonomic layout is to have the external monitor positioned on the top of the primary one.

With this layout, wingpanel prevents windows to be dragged from the bottom screen to the upper screen, so that it is unusable in practice.

Please change the behavior so that windows can be moved over the panel (like it is done with the Gnome panel, for instance).

**Comment by cassidyjames** [comment] 2018-01-27 18:55
Thanks for filing! I believe this is a duplicate of #33, now tracked at https://github.com/elementary/gala/issues/7. If not, let me know and we can re-open this.

**Closed by cassidyjames** 2018-01-27 18:55 UTC
