### ISSUE TITLE
Support indicators for 3rd party applications

### ISSUE THREAD

**Issue by rdanter** [elementary/wingpanel#431] opened 2021-12-29 15:26 UTC
### Problem

I'm sure this has been brought up before but I want to raise it again because it is really frustrating.

I use multiple desktops and machines so I use tools like Dropbox for sharing files. The indicator works on every desktop and OS I use except eOS. I can get it by following the steps here:

https://elementaryos.stackexchange.com/questions/28500/tray-icon-support-in-elementary-6-odin-single-click-in-file-manager

but this is not something I think most beginner users would be comfortable doing.

It's not just Dropbox, indicators for Telegram and other chat programs also use what I think are "standard" indicators. Not having this work out of the box makes it difficult for anyone new to eOS whether absolute beginners or just those moving from other desktops.

### Proposal

Proposal is to have the wingpanel-indicator-ayatana included and enabled by default.

**Comment by cassidyjames** [comment] 2022-01-01 16:33
Duplicate of #96, see https://github.com/elementary/wingpanel/issues/96#issuecomment-401412541 and https://islinuxabout.xyz/systray/ for more info.

**Closed** 2022-01-01 16:33 UTC
