### ISSUE TITLE
Wingpanel lost full transparency

### ISSUE THREAD

**Issue by activey** [elementary/wingpanel#512] opened 2023-11-08 08:17 UTC
### What Happened?

Recently rebooted my desktop after a long while (a week or so) and noticed it's no longer fully transparent, its semi transparent like in gnome. Full transparency with pretty shadows under the icons was ONE of the reasons I use elementary over gnome. 

### Steps to Reproduce

Hard to say, didn't do anything.

### Expected Behavior

It should be fully transparent, not semi-transparent like on sh...y gnome.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by activey** [comment] 2023-11-08 08:17
This is how it looks now:

![image](https://github.com/elementary/wingpanel/assets/1751891/36ba8c32-42c3-40b4-998a-1d75cf4641b0)

**Comment by activey** [comment] 2023-11-08 09:57
It does not happen when I change desktop wallpaper to slightly darker (??).

**Comment by tnetenbaa** [comment] 2024-05-20 05:38
Are you using a different theme than default? I know some themes change the panel.

**Comment by lenemter** [comment] 2024-08-14 10:30
Duplicate of https://github.com/elementary/wingpanel/issues/137

**Closed by lenemter** 2024-08-14 10:30 UTC
