### ISSUE TITLE
Window flickers when navigating between Wingpanel indicators

### ISSUE THREAD

**Issue by Appeltabak** [elementary/wingpanel#263] opened 2019-11-01 08:44 UTC
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
When navigating through the Wingpanel indicators, the application window that had been focused flashes/flickers, seemingly changing from focused to unfocused (see screencast).

### To Reproduce
1. Open any application
2. Navigate through the indicator as demonstrated in the screencast
3. Notice the flashing 

### Expected behavior
Don't change the focus of the application.

### Screenshots or screen recordings
![Screen record from 2019-11-01 09 38 38](https://user-images.githubusercontent.com/6260588/68012848-7bd94100-fc8b-11e9-9d09-44bdcf93208a.gif)

## Platform Information
![image](https://user-images.githubusercontent.com/6260588/68012998-f6a25c00-fc8b-11e9-9dd8-25ec0ee8b9a6.png)

Please check what applies:
- [ ] I'm using the latest version from git that I've manually compiled
- [X] I'm using the latest released stable version

**Comment by 4jNsY6fCVqZv** [comment] 2019-11-01 21:16
Looks like the issue isn't fixed with https://github.com/elementary/wingpanel/pull/222# after all. I can confirm that it still exists after the new Wingpanel release.

**Comment by 4jNsY6fCVqZv** [comment] 2019-11-02 08:52
This was fixed with the last release https://github.com/elementary/wingpanel/releases/tag/2.2.6

However, you must first restart Wingpanel to see the changes. As far as I know, an update via the AppCenter is not enough. Just as it is the case with the update of the AppCenter itself.

As an idea: Perhaps AppCenter can simply give users a hint whenever some changes can only take effect by restarting the components. And at the same time offers an action to do so.

Or is it possible that changes can basically happen live and the corresponding components update themselves and restart themselves if necessary?

**Comment by janxkoci** [comment] 2019-11-10 12:28
I think the apps/components should know best when they need restart to finish update properly - I don't see why AppCenter should be responsible for that (except kernel updates, which nearly always require reboots, unless you use something like livepatch).

**Comment by peteruithoven** [comment] 2019-12-08 16:44
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/wingpanel/issues/221

**Closed by peteruithoven** 2019-12-08 16:44 UTC
