### ISSUE TITLE
Dinamic transparency isn't working with multiple displays

### ISSUE THREAD

**Issue by apcamargo** [elementary/wingpanel#184] opened 2018-12-29 21:41 UTC
I connected my laptop to an external display and set it to be my primary display. I've noticed that Wingpanel stays semi-transparent black regardless of my wallpaper.

![screenshot from 2018-12-29 18 47 28](https://user-images.githubusercontent.com/22940964/50542105-a229de00-0b9b-11e9-8472-dee1eb9f8b15.png)

**Comment by kr428** [comment] 2019-03-08 21:06
Adding myself to this, though I am not completely sure I'm affected by the same issue. Screenshots:

![Uploading Screenshot von 2019-03-08 07.45.42.png…](semi-transparent background)
![Uploading Screenshot von 2019-03-08 20.38.15.png…](transparent background)

My setup also includes a secondary display connected via DisplayPort and an USB-C dock. The laptop display usually is disabled via xrandr (because of https://github.com/elementary/switchboard-plug-display/issues/131#issuecomment-431614833). 

However, I can't reproduce this issue to be fully related to the secondary display. In some cases (after unlocking the screen for a couple of times?), the panel is fully transparent on the secondary monitor as well. So far I failed to find a real reliable pattern for that.

**Comment by SilverWolf32** [comment] 2019-03-28 22:15
I have this problem as well; when I unplug my external display (connected with a Thunderbolt-to-DVI adapter) and kill wingpanel, the problem goes away. When I plug it back in and kill wingpanel again, it goes partially opaque again. My primary display is the internal one.

Also, my panel does switch between dark and light depending on the background. It just stays opaque while doing it.

**Comment by kr428** [comment] 2019-04-08 08:58
Interesting insight here: If I just boot my laptop and log in with only the laptop display enabled and plug the external monitor after logging in, this problem doesn't exist.

**Comment by lenemter** [comment] 2024-08-14 11:04
Fixed in OS 8

**Closed by lenemter** 2024-08-14 11:04 UTC
