### ISSUE TITLE
Wingpanel animation during Multitask view

### ISSUE THREAD

**Issue by mluizvitor** [elementary/wingpanel#473] opened 2023-02-06 23:38 UTC
### What Happened?

When triggering a hot corner to close Applications menu while in Multitask view, Wingpanel shows scaled 100% of the screen height and shrinks until desapear.

[Screen record from 2023-02-06 20.32.23.webm](https://user-images.githubusercontent.com/57257682/217110929-6a02d8da-f2c0-413b-8459-594b178190d1.webm)

### Steps to Reproduce

1. Open Settings -> Desktop -> Multitask
2. Top left croner: Show Applications menu (something like this, I'm using another language)
3. Open the Multitasking view
4. Move your mouse to the top left corner to open the Applications menu while in multitask view.
5. Move the mouse away and go back to the corner to close the menu.
6. The odd animation starts.

Any corner triggers the same behavior.

### Expected Behavior

The Wingpanel shouldn't appear at any moment. Or block the activation of Applications menu. Both during Multitask view.

### OS Version

7.x (Early Access)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment] 2023-02-06 23:45
This is duplicate of elementary/gala#1483 which has been fixed recently

**Closed by lenemter** 2023-02-06 23:45 UTC
