### ISSUE TITLE
wingpanel gap with fullscreen apps

### ISSUE THREAD

**Issue by juanfgs** [elementary/wingpanel#112] opened 2018-05-12 18:47 UTC
Hello, I'm using ~elementary~ Pantheon on Fedora. I don't know if this is a bug in the elementary theme or in wingpanel, but whenever wingpanel first starts (after lightdm) there is a small gap between maximized windows. It's like wingpanel wasn't able to fully allocate it's height.

If I kill wingpanel (and cerbere starts it again) the problem fixes . 

![captura de pantalla de 2018-05-12 15-43-16](https://user-images.githubusercontent.com/507984/39960583-c4d7a79e-55fb-11e8-859d-37fd6cbefdf2.png)
![captura de pantalla de 2018-05-12 15-45-29](https://user-images.githubusercontent.com/507984/39960584-c50712f4-55fb-11e8-9108-37b359861938.png)

Oddly enough this only happens with Elementary theme, if I switch to another theme, the panel appears correctly even after logging into a new session. see:

![captura de pantalla de 2018-05-12 15-51-30](https://user-images.githubusercontent.com/507984/39960612-5d72d1c2-55fc-11e8-9fd8-ff4672b3130a.png)

From what I've measured it seems like some sort of margin is being applied, the wingpanel height only differs in one pixel, yet the gap itself is of about 4 pixels.

Let me know what other information can be useful to debug this.

**Comment by Djaler** [comment] 2018-05-12 20:26
I can confirm this. Sometimes I faced into this

**Comment by danrabbit** [comment] 2018-05-12 23:25
Closing as a duplicate of #69

**Closed by danrabbit** 2018-05-12 23:25 UTC
