### ISSUE TITLE
wingpanel crashes randomly

### ISSUE THREAD

**Issue by b4shx0r** [elementary/wingpanel#416] opened 2021-10-18 19:18 UTC
### What Happened?

I'm on latest odin (fresh instlal no upgrade) - wingpanel crashes randomly. The time freezes and no click on application menu is possible.

my workaround is I use killall io.elementary.wingpanel to restart the wingpanel process.

are there any logs or a debug mode?

io.elementary.wingpanel --help does not show up a debug option.

The only modification is I have installed the system monitor plugin:
https://github.com/diogopessoa/wingpanel-indicator-sysmon

### Steps to Reproduce

randomly 4-5 crashes a day

### Expected Behavior

no random crashes

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

**Comment by tarik-boumaza** [comment] 2021-11-25 14:24
**_Same issue_**

i have been using elementary os for over 2 years and wingpanel crashes almost every day and at random. I have to `kill` it from the terminal to restart it.

**Comment by tintou** [comment] 2021-11-25 14:51
We likely need some traces to understand what is happening:
1. Install systemd-coredump and enable Ubuntu debug packages
```bash
sudo apt install systemd-coredump ubuntu-dbgsym-keyring
echo "deb http://ddebs.ubuntu.com $(lsb_release -csu)-updates main restricted universe multiverse\ndeb http://ddebs.ubuntu.com $(lsb_release -csu)-proposed main restricted universe multiverse\ndeb http://ddebs.ubuntu.com $(lsb_release -csu) main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ddebs.list
 ```
2. Modify `/etc/apt/sources.list.d/elementary-os-ubuntu-stable-focal.list` to include `main/debug` at then end of the first line, like:
```
deb http://ppa.launchpad.net/elementary-os/daily/ubuntu focal main main/debug
```
3. Install the debug symbols for a complete backtrace of >ingpanel
```bash
sudo apt update
sudo apt install libglib2.0-0-dbgsym libgtk-3-0-dbgsym io.elementary.wingpanel-dbgsym libwingpanel3-dbgsym wingpanel-indicator-bluetooth-dbgsym wingpanel-indicator-datetime-dbgsym wingpanel-indicator-keyboard-dbgsym wingpanel-indicator-network-dbgsym wingpanel-indicator-nightlight-dbgsym wingpanel-indicator-notifications-dbgsym wingpanel-indicator-power-dbgsym wingpanel-indicator-session-dbgsym wingpanel-indicator-sound-dbgsym
```
4. Make wingpanel crash
5. Run and copy here the output of:
```bash
sudo coredumpctl dump /usr/bin/io.elementary.wingpanel
```

Thank you for your cooperation

**Comment by tarik-boumaza** [comment] 2021-11-25 15:59
1. Since I did this, I got a lot of warnings on `sudo apt update`. Some of them (translated from french):
```
W: The configured file "bionic-proposed/cnf /Commands-amd64" will not be taken into account because the repository "http://ddebs.ubuntu.com bionic-updates InRelease" does not have the source "bionic-proposed "(Input error in sources.list?)
W: The configured file "bionic/binary-amd64/Packages" will not be taken into account because the repository "http://ddebs.ubuntu.com bionic-updates InRelease" does not have the source "bionic" (error of entered in sources.list?) 
```
You can also review them here : [warning.txt](https://github.com/elementary/wingpanel/files/7604142/warning.txt)
2. The file `/etc/apt/sources.list.d/elementary-os-ubuntu-stable-focal.list` does not exit, I have a similar one : `/etc/apt/sources.list.d/elementary-os-ubuntu-daily-bionic.list`

Is this related to a different version of eOS?

**Comment by tintou** [comment] 2021-11-25 16:03
@tarik-boumaza Sorry, the report above mentioned Odin (Based on Ubuntu Focal), you seem to be on Juno (based on Ubuntu Bionic)

We are unlikely to fix any issue on Juno these days

**Comment by vjr** [comment] 2021-11-26 02:30
@tintou  are these kind of debugging instructions available on the elementary website for easy discoverable?

**Comment by tintou** [comment] 2021-11-26 10:02
@vjr It's not and I'm actually recreating the instructions from memory every time I have to ask them :sweat_smile:

**Comment by canopusStar** [comment] 2022-01-23 00:35
> We likely need some traces to understand what is happening:
> 
>     1. Install systemd-coredump and enable Ubuntu debug packages
> 
> 
> ```shell
> sudo apt install systemd-coredump ubuntu-dbgsym-keyring
> echo "deb http://ddebs.ubuntu.com $(lsb_release -csu)-updates main restricted universe multiverse\ndeb http://ddebs.ubuntu.com $(lsb_release -csu)-proposed main restricted universe multiverse\ndeb http://ddebs.ubuntu.com $(lsb_release -csu) main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ddebs.list
> ```
> 
>     2. Modify `/etc/apt/sources.list.d/elementary-os-ubuntu-stable-focal.list` to include `main/debug` at then end of the first line, like:
> 
> 
> ```
> deb http://ppa.launchpad.net/elementary-os/daily/ubuntu focal main main/debug
> ```
> 
>     3. Install the debug symbols for a complete backtrace of >ingpanel
> 
> 
> ```shell
> sudo apt update
> sudo apt install libglib2.0-0-dbgsym libgtk-3-0-dbgsym io.elementary.wingpanel-dbgsym libwingpanel3-dbgsym wingpanel-indicator-bluetooth-dbgsym wingpanel-indicator-datetime-dbgsym wingpanel-indicator-keyboard-dbgsym wingpanel-indicator-network-dbgsym wingpanel-indicator-nightlight-dbgsym wingpanel-indicator-notifications-dbgsym wingpanel-indicator-power-dbgsym wingpanel-indicator-session-dbgsym wingpanel-indicator-sound-dbgsym
> ```
> 
>     4. Make wingpanel crash
> 
>     5. Run and copy here the output of:
> 
> 
> ```shell
> sudo coredumpctl dump /usr/bin/io.elementary.wingpanel
> ```
> 
> Thank you for your cooperation

I have the same issue with a wingpanel that now crashes when anything on it is clicked. It recovers and then crashes again. I am using ODIN 6.1 with full updates. 
I have tried killing winpanel, reinstalling it - same issue
I attempted to follow your back trace instructions and got this result:

wemax@wemax-780:/etc/apt/sources.list.d$ sudo apt install libglib2.0-0-dbgsym libgtk-3-0-dbgsym io.elementary.wingpanel-dbgsym libwingpanel3-dbgsym wingpanel-indicator-bluetooth-dbgsym wingpanel-indicator-datetime-dbgsym wingpanel-indicator-keyboard-dbgsym wingpanel-indicator-network-dbgsym wingpanel-indicator-nightlight-dbgsym wingpanel-indicator-notifications-dbgsym wingpanel-indicator-power-dbgsym wingpanel-indicator-session-dbgsym wingpanel-indicator-sound-dbgsym
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package io.elementary.wingpanel-dbgsym
E: Couldn't find any package by glob 'io.elementary.wingpanel-dbgsym'
E: Unable to locate package libwingpanel3-dbgsym
E: Unable to locate package wingpanel-indicator-bluetooth-dbgsym
E: Unable to locate package wingpanel-indicator-datetime-dbgsym
E: Unable to locate package wingpanel-indicator-keyboard-dbgsym
E: Unable to locate package wingpanel-indicator-network-dbgsym
E: Unable to locate package wingpanel-indicator-nightlight-dbgsym
E: Unable to locate package wingpanel-indicator-notifications-dbgsym
E: Unable to locate package wingpanel-indicator-power-dbgsym
E: Unable to locate package wingpanel-indicator-session-dbgsym
E: Unable to locate package wingpanel-indicator-sound-dbgsym
wemax@wemax-780:/etc/apt/sources.list.d$ 

Wingpanel at this stage is unusable.

**Comment by gjedlicska** [comment] 2022-03-02 22:35
hey, there is an bit of an issue with the instructions above, the echo command in step 1 doesn't insert the newline characters as intended, instead, it leaves them in the file.
Make sure your `/etc/apt/sources.list.d/ddebs.list` looks like this
![image](https://user-images.githubusercontent.com/57442769/156461233-793ae2d3-8522-4ec0-86f6-b5bc2c57ec90.png)

Btw i'm also hit with this issue, wingpanel uses 100% of a CPU core and after a while it crashes. Trying to repro to provide some traceback.

**Comment by jeremypw** [comment] 2022-03-03 10:44
Possible related to https://github.com/elementary/wingpanel-indicator-notifications/issues/123.

**Comment by peteruithoven** [comment] 2022-04-05 13:08
( @vjr @tintou There is some relevant how to debug info in this section of the website: https://docs.elementary.io/contributor-guide/ )

**Comment by jams01** [comment] 2022-04-05 20:57
I opened wingpanel from the terminal as described in the guide. The freezing problem appears when the bell icon is clicked and after that, if I click anywhere on the screen, these 3 log lines are shown,

`(io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed

(io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed`

 and the only way to change the focused window is with alt + tab because it looks as if the mouse click stopped working. The only way to get it to work again is by killing wing panel. Here is the whole log

[wingpanellog.log](https://github.com/elementary/wingpanel/files/8421776/wingpanellog.log)

**Comment by canopusStar** [comment] 2022-04-06 05:42
> I opened wingpanel from the terminal as described in the guide. The freezing problem appears when the bell icon is clicked and after that, if I click anywhere on the screen, these 3 log lines are shown,
> 
> `(io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_parent: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> (io.elementary.wingpanel:17701): Gtk-CRITICAL **: 15:43:48.186: gtk_widget_get_allocation: assertion 'GTK_IS_WIDGET (widget)' failed`
> 
> and the only way to change the focused window is with alt + tab because it looks as if the mouse click stopped working. The only way to get it to work again is by killing wing panel. Here is the whole log
> 
> [wingpanellog.log](https://github.com/elementary/wingpanel/files/8421776/wingpanellog.log)

Several issue reports similar to yours indicate the following solution:  rm ~/.cache/.notifications.session

**Comment by jams01** [comment] 2022-04-07 20:27
Nice, It works smoothly now.

**Comment by peteruithoven** [comment] 2023-04-15 10:49
Looks like the underlying problem is https://github.com/elementary/wingpanel/issues/442, let's close this issue for now?

**Closed by peteruithoven** 2023-04-15 10:49 UTC
