### ISSUE TITLE
Opaque wingpanel

### ISSUE THREAD

**Issue by h2ash** [elementary/wingpanel#216] opened 2019-05-24 14:59 UTC
Wingpanel became opaque and white after eOS had updated. It's hitting the eyes on this wallpaper.

The background was transparent. That was great.  
https://picua.org/image/iOVaMF

Screenshot with issue:
https://picua.org/image/iOMq2z

**Comment by peteruithoven** [comment] 2019-05-24 15:04
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/wingpanel/issues/207
This was fixed with: https://github.com/elementary/wingpanel/pull/208
But there hasn't been a new release yet. 

Btw, you can include images in your github message directly.

**Closed by peteruithoven** 2019-05-24 15:04 UTC
