### ISSUE TITLE
When using two monitors, Wingpanel's background/applet colour does not automatically update with wallpaper change.

### ISSUE THREAD

**Issue by jakewn** [elementary/wingpanel#128] opened 2018-07-04 13:28 UTC
Happening on nvidia 390 drivers, dual 1080p if that makes a difference. Tested by unplugging one monitor and changing wallpaper.

**Comment by lenemter** [comment] 2023-07-20 05:16
I'll close this as duplicate of https://github.com/elementary/wingpanel/issues/358 because it got more attention.

**Closed by lenemter** 2023-07-20 05:16 UTC
