### ISSUE TITLE
Dynamic colour/background doesn't work after logout.

### ISSUE THREAD

**Issue by Blast-City** [elementary/wingpanel#352] opened 2020-10-06 17:01 UTC
1- Go to settings and choose the snowy mountains wallpaper (Canazei Granite Ridges.jpg).
2- Logout and Login.

**Result:** The wingpanel doesn't have the black font on a transparent background any more. This seems to happen because the wingpanel appears before the wallpaper when the screen is still black which makes it select the default colour (white font on transparent background). This doesn't seem to happen if on the step "2" a user chooses to reboot instead.

**Comment by cassidyjames** [comment] 2020-10-06 22:14
Thanks for reporting! This is actually a duplicate of https://github.com/elementary/gala/issues/613

**Closed by cassidyjames** 2020-10-06 22:14 UTC
