### ISSUE TITLE
Support switching power profile from battery status icon popup menu

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/wingpanel#463] opened 2022-08-25 20:15 UTC
### Problem

When travelling with train, I often need to switch power profiles as some follow-up trains might not have AC power available or it is not working. In that case, I want to save as much power as I can with as little effort as possible.

I don't want to go through all the menus in the system settings to reach the power profile setting (I think I saw that such power profiles are about to be introduced with elementary 7.0, did I get that right)

### Proposal

Provide all available power profiles as clickable items in the battery icon popup (when I click the battery in the top bar with left mouse button single click).

Optional: display a nice "flat" themed icon next to the battery to indicate which power profile is currently active, e.g. a leaf for maximum power save mode

**Comment by lenemter** [comment] 2022-08-26 09:59
I guess it's a duplicate of elementary/wingpanel-indicator-power#132
Proposed fix: elementary/wingpanel-indicator-power#220

**Closed by lenemter** 2022-08-26 09:59 UTC
